repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
